"""
HOC State Machine wrapper over ``tramoya`` (Phase 4)
====================================================

This module isolates HOC from the ``tramoya`` API surface. HOC code never
imports ``tramoya`` directly; it imports :class:`HocStateMachine` from
:mod:`hoc.state_machines.base`. The same isolation tactic Phase 2 used for
``mscs`` in :mod:`hoc.security`: a thin typed wrapper at the boundary so
upstream API drift is absorbed in one place.

Why a wrapper?
--------------

1. **Caller ergonomics.** ``tramoya.Machine`` is event-driven: callers fire
   *named triggers* and the engine resolves the destination. HOC's
   pre-Phase-4 code does ``cell.state = NEW_STATE`` directly — *destination-
   driven*. The wrapper exposes :meth:`HocStateMachine.transition_to` which
   takes a target state name, looks up the trigger that produces that
   transition from the current state, and fires it.

2. **Typed exception surface.** ``tramoya`` raises
   :class:`tramoya.InvalidTransition` and :class:`tramoya.GuardRejected`.
   HOC raises :class:`IllegalStateTransition` (single, contextful exception
   with the FSM name in the message). Callers do not need to know which
   library produced the rejection.

3. **Phase-3-style API stability.** Future swaps of the FSM library only
   touch this file; downstream FSM modules
   (:mod:`hoc.state_machines.cell_fsm`, etc.) and call-sites stay the same.

Usage
-----

::

    from hoc.state_machines import HocStateMachine, HocTransition

    fsm = HocStateMachine(
        name="cell",
        states=["EMPTY", "IDLE", "ACTIVE", "FAILED"],
        transitions=[
            HocTransition("EMPTY", "IDLE"),
            HocTransition("IDLE", "ACTIVE"),
            HocTransition("ACTIVE", "IDLE"),
            HocTransition("ACTIVE", "FAILED"),
        ],
        initial="EMPTY",
    )

    fsm.transition_to("IDLE")     # EMPTY -> IDLE
    fsm.transition_to("ACTIVE")   # IDLE -> ACTIVE
    fsm.transition_to("EMPTY")    # raises IllegalStateTransition: no path
"""

from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from typing import Any, cast

import tramoya as _tramoya

WILDCARD: str = _tramoya.WILDCARD

# ─── Exceptions ───────────────────────────────────────────────────────────────


class IllegalStateTransition(Exception):
    """
    Raised when a requested transition is not permitted by the FSM.

    Two conditions trigger this:

    1. **No edge.** No transition is declared from ``current`` to ``target``
       (or via wildcard) — :attr:`reason` is ``"no_edge"``.
    2. **Guard rejected.** Edges exist but every applicable guard returned
       ``False`` for the supplied context — :attr:`reason` is
       ``"guard_rejected"``.

    The ``fsm_name``, ``source``, ``target``, and ``reason`` are exposed as
    attributes so callers (e.g. metrics emitters) can branch without
    parsing the message string.
    """

    def __init__(
        self,
        fsm_name: str,
        source: str,
        target: str,
        reason: str,
        cause: BaseException | None = None,
    ) -> None:
        self.fsm_name = fsm_name
        self.source = source
        self.target = target
        self.reason = reason
        msg = f"[{fsm_name}] illegal transition '{source}' -> '{target}' ({reason})"
        super().__init__(msg)
        if cause is not None:
            self.__cause__ = cause


# ─── Transition declaration ───────────────────────────────────────────────────

GuardFn = Callable[[Mapping[str, Any]], bool]
ActionFn = Callable[[dict[str, Any]], None]
HookFn = Callable[[dict[str, Any]], None]
ObserverFn = Callable[[str, str, str, Mapping[str, Any]], None]


@dataclass(frozen=True)
class HocTransition:
    """
    Declarative description of a single edge in a HOC state machine.

    ``source`` and ``dest`` are state name strings. ``source`` may be
    :data:`WILDCARD` (``"*"``) to match any current state.

    ``trigger`` is optional; if omitted, a deterministic synthetic trigger
    name is generated by :class:`HocStateMachine` (``"<source>__to__<dest>"``).
    Provide an explicit ``trigger`` only when callers need to fire it by
    name through :meth:`HocStateMachine.trigger`.

    ``guard`` runs against a frozen view of the FSM context. It must not
    mutate the context. Returning ``False`` blocks the transition; the
    caller sees :class:`IllegalStateTransition` with ``reason="guard_rejected"``.

    ``action`` runs after the guard passes and before ``on_enter`` of
    the destination. It may mutate the context dict.
    """

    source: str
    dest: str
    trigger: str | None = None
    guard: GuardFn | None = None
    action: ActionFn | None = None


# ─── Wrapper ──────────────────────────────────────────────────────────────────


class HocStateMachine:
    """
    Typed adapter around :class:`tramoya.Machine` for HOC.

    Construction is declarative: pass states, transitions, hooks. The
    wrapper builds the underlying ``tramoya.Machine`` and exposes a
    destination-driven API (:meth:`transition_to`) plus the trigger-driven
    one (:meth:`trigger`) for callers that prefer events.

    The wrapper does **not** subclass ``tramoya.Machine`` to keep the
    boundary explicit and the upstream API at arm's length.
    """

    def __init__(
        self,
        *,
        name: str,
        states: Sequence[str],
        transitions: Sequence[HocTransition],
        initial: str,
        on_enter: Mapping[str, HookFn] | None = None,
        on_exit: Mapping[str, HookFn] | None = None,
        on_transition: ObserverFn | None = None,
        ctx: Mapping[str, Any] | None = None,
        history_size: int = 50,
    ) -> None:
        if not name:
            raise ValueError("HocStateMachine requires a non-empty name")

        self._name = name
        # dest -> [(source, trigger), ...] in declaration order.
        # transition_to() walks this index to find the right trigger to fire.
        self._dest_index: dict[str, list[tuple[str, str]]] = {}

        tramoya_transitions: list[tuple[Any, ...]] = []
        seen_triggers: set[str] = set()
        for idx, t in enumerate(transitions):
            trigger_name = t.trigger or f"{t.source}__to__{t.dest}"
            # Disambiguate auto-generated names if multiple edges collapse:
            # e.g. wildcard + explicit can both target the same dest. Append
            # the index to keep deterministic uniqueness.
            if trigger_name in seen_triggers:
                trigger_name = f"{trigger_name}__{idx}"
            seen_triggers.add(trigger_name)

            tramoya_transitions.append((trigger_name, t.source, t.dest, t.guard, t.action))
            self._dest_index.setdefault(t.dest, []).append((t.source, trigger_name))

        self._machine = _tramoya.Machine(
            states=list(states),
            transitions=tramoya_transitions,
            initial=initial,
            on_enter=dict(on_enter) if on_enter else None,
            on_exit=dict(on_exit) if on_exit else None,
            on_transition=on_transition,
            ctx=dict(ctx) if ctx else None,
            history_size=history_size,
        )

    # ── Identity ──────────────────────────────────────────────────────────

    @property
    def name(self) -> str:
        return self._name

    @property
    def state(self) -> str:
        return cast(str, self._machine.state)

    @property
    def states(self) -> set[str]:
        return cast("set[str]", self._machine.states)

    @property
    def initial(self) -> str:
        return cast(str, self._machine.initial)

    @property
    def history(self) -> list[str]:
        """Previous state names (most recent last)."""
        return cast("list[str]", self._machine.history)

    @property
    def ctx(self) -> dict[str, Any]:
        """Mutable context dict carried through the machine."""
        return cast("dict[str, Any]", self._machine.ctx)

    @property
    def transitions(self) -> list[tuple[str, str, str]]:
        """All declared edges as ``(source, dest, trigger)`` triples.

        Source may be :data:`WILDCARD`. Order matches construction order.
        Used by the static-checker (``choreo``) to walk the spec graph
        without touching ``_dest_index`` directly.
        """
        result: list[tuple[str, str, str]] = []
        for dest, pairs in self._dest_index.items():
            for source, trigger in pairs:
                result.append((source, dest, trigger))
        return result

    # ── Destination-driven API ────────────────────────────────────────────

    def can_transition_to(self, target: str, **ctx_kwargs: Any) -> bool:
        """
        Check whether :meth:`transition_to` would succeed for ``target``.
        Evaluates guards. Does not fire any callbacks.
        """
        if target not in self._machine.states:
            return False
        candidates = self._dest_index.get(target, [])
        current = self._machine.state
        # Explicit source matches take priority over wildcard, mirroring
        # tramoya's _match_candidates ordering.
        explicit = [trigger for src, trigger in candidates if src == current]
        wildcard = [trigger for src, trigger in candidates if src == WILDCARD]
        return any(self._machine.can(trigger, **ctx_kwargs) for trigger in explicit + wildcard)

    def transition_to(self, target: str, **ctx_kwargs: Any) -> str:
        """
        Move the FSM to ``target``. Returns the new state name.

        Raises :class:`IllegalStateTransition` if no edge exists from the
        current state to ``target``, or if every applicable guard rejected
        the supplied context.

        Side effects (``on_exit``, action, ``on_enter``, ``on_transition``)
        fire in tramoya's documented order. If any callback raises, the
        underlying engine rolls back state and context to pre-transition.
        """
        if target not in self._machine.states:
            raise IllegalStateTransition(
                self._name, self._machine.state, target, reason="unknown_state"
            )

        current = self._machine.state
        candidates = self._dest_index.get(target, [])
        explicit = [trigger for src, trigger in candidates if src == current]
        wildcard = [trigger for src, trigger in candidates if src == WILDCARD]
        ordered = explicit + wildcard

        if not ordered:
            raise IllegalStateTransition(self._name, current, target, reason="no_edge")

        last_error: BaseException | None = None
        for trigger_name in ordered:
            try:
                return cast(str, self._machine.trigger(trigger_name, **ctx_kwargs))
            except _tramoya.GuardRejected as exc:
                last_error = exc
                continue
            except _tramoya.InvalidTransition as exc:
                # Should not happen given our index, but keep it as a
                # fail-safe rather than swallow.
                last_error = exc
                continue

        raise IllegalStateTransition(
            self._name,
            current,
            target,
            reason="guard_rejected",
            cause=last_error,
        )

    # ── Trigger-driven API (passthrough) ──────────────────────────────────

    def can(self, trigger: str, **ctx_kwargs: Any) -> bool:
        """Whether ``trigger`` would fire from the current state."""
        return cast(bool, self._machine.can(trigger, **ctx_kwargs))

    def trigger(self, trigger: str, **ctx_kwargs: Any) -> str:
        """Fire a named trigger. Returns the new state. Raises
        :class:`IllegalStateTransition` instead of tramoya's exceptions."""
        try:
            return cast(str, self._machine.trigger(trigger, **ctx_kwargs))
        except _tramoya.InvalidTransition as exc:
            raise IllegalStateTransition(
                self._name,
                self._machine.state,
                target=f"<trigger:{trigger}>",
                reason="no_edge",
                cause=exc,
            ) from exc
        except _tramoya.GuardRejected as exc:
            raise IllegalStateTransition(
                self._name,
                self._machine.state,
                target=f"<trigger:{trigger}>",
                reason="guard_rejected",
                cause=exc,
            ) from exc

    @property
    def available_triggers(self) -> list[str]:
        return cast("list[str]", self._machine.available_triggers)

    @property
    def is_final(self) -> bool:
        """``True`` if the current state has no outgoing transitions
        (ignores guards). Useful for asserting terminal-state invariants
        in property tests."""
        return cast(bool, self._machine.is_final)

    def is_stuck(self, **ctx_kwargs: Any) -> bool:
        """``True`` if no trigger can fire from the current state, given
        the supplied context (evaluates guards)."""
        return cast(bool, self._machine.is_stuck(**ctx_kwargs))

    # ── Undo / reset ──────────────────────────────────────────────────────

    def undo(self) -> str:
        """Revert one transition. State + ctx restored to pre-transition.
        Hooks do **not** fire on undo. External side effects are not
        reverted (caller's responsibility — typical use: pair undo with a
        compensating action like releasing a workload back to the source)."""
        try:
            return cast(str, self._machine.undo())
        except _tramoya.MachineError as exc:
            raise IllegalStateTransition(
                self._name,
                self._machine.state,
                target="<undo>",
                reason="empty_history",
                cause=exc,
            ) from exc

    def reset(self, state: str | None = None) -> None:
        """Reset to the initial state (or to ``state`` if provided)."""
        try:
            self._machine.reset(state)
        except _tramoya.MachineError as exc:
            raise IllegalStateTransition(
                self._name,
                self._machine.state,
                target=state or self.initial,
                reason="unknown_state",
                cause=exc,
            ) from exc

    # ── Observers ─────────────────────────────────────────────────────────

    def subscribe(self, observer: ObserverFn) -> ObserverFn:
        """Register an observer. ``observer(trigger, src, dst, ctx)``.
        Returns the same callable for use as a decorator or unsubscribe handle."""
        self._machine.subscribe(observer)
        return observer

    def unsubscribe(self, observer: ObserverFn) -> None:
        self._machine.unsubscribe(observer)

    # ── Visualization ─────────────────────────────────────────────────────

    def to_mermaid(self) -> str:
        """Mermaid ``stateDiagram-v2`` source. Deterministic for a given FSM
        spec — useful for snapshot tests and ``docs/state-machines.md``."""
        return cast(str, self._machine.to_mermaid())

    def to_dot(self) -> str:
        """Graphviz DOT source. Deterministic."""
        return cast(str, self._machine.to_dot(title=self._name))

    # ── Repr ──────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        return (
            f"HocStateMachine(name={self._name!r}, "
            f"state={self._machine.state!r}, "
            f"triggers={self.available_triggers})"
        )
